Removing support for Python 3.4
Due to:

```
Running lxml-4.4.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-l1h619s8/lxml-4.4.0/egg-dist-tmp-9bb36bhi

This lxml version requires Python 2.7, 3.5 or later.

error: Setup script exited with 1
```