Fix JP2 format detection
This appears to have been a confusion between filemagic and python-magic,
but not sure where the regression would have been introduced. It was erroring
with:

    exception: __enter__

Which was a suppression of the original error:

    AttributeError: 'Magic' object has no attribute 'id_buffer'